---
hide_table_of_contents: true
hide_title: true
custom_edit_url: null
---

import CenterLayout from "/src/components/CenterLayout"
import GitHub from "/src/components/GitHub"

<head>
  <link rel="canonical" href="https://github.com/gruntwork-io/knowledge-base/discussions/666" />
</head>

<CenterLayout>
<span className="searchCategory">Knowledge Base</span>
<h1>terraform CI/CD pipeline, &quot;Repository not found&quot;</h1>
<GitHub discussion={{"id":"D_kwDOF8slf84ASkV1","number":666,"author":{"login":"jeffreymlewis"},"title":"terraform CI/CD pipeline, \"Repository not found\"","body":"\r\nOur Gruntwork CI/CD pipeline suddenly stopped working with errors like the following. Anyone else running into this? I'm thinking either github changed something, or my token(s) have expired.\r\n\r\n```\r\n[ecs-deploy-runner][2023-02-17T00:24:22+0000] \t* error downloading 'ssh://git@github.com/org/repo.git?ref=v0.94.1': /usr/bin/git exited with 128: Cloning into '/tmp/tmpltkuc0gw/dev/*********/dev/services/eks-cluster/repo/.terragrunt-cache/KT2kgJFUCMt8sVayfunMQ6a7wrg/MmsVrBnwzYe18iyiPxhzDEVSfKw'...\r\n[ecs-deploy-runner][2023-02-17T00:24:22+0000] remote: Repository not found.\r\n[ecs-deploy-runner][2023-02-17T00:24:22+0000] fatal: repository 'https://github.com/org/repo.git/' not found\r\n```\r\n\r\nFor reference, this is trying to clone a private repo. I re-ran a workflow from yesterday, and the `plan` failed with the above error.\r\n\r\n---\r\n\r\n<ins datetime=\"2023-02-17T00:42:27Z\">\r\n  <p><a href=\"https://support.gruntwork.io/hc/requests/109908\">Tracked in ticket #109908</a></p>\r\n</ins>\r\n","bodyHTML":"<p dir=\"auto\">Our Gruntwork CI/CD pipeline suddenly stopped working with errors like the following. Anyone else running into this? I'm thinking either github changed something, or my token(s) have expired.</p>\n<div class=\"snippet-clipboard-content notranslate position-relative overflow-auto\" data-snippet-clipboard-copy-content=\"[ecs-deploy-runner][2023-02-17T00:24:22+0000] \t* error downloading 'ssh://git@github.com/org/repo.git?ref=v0.94.1': /usr/bin/git exited with 128: Cloning into '/tmp/tmpltkuc0gw/dev/*********/dev/services/eks-cluster/repo/.terragrunt-cache/KT2kgJFUCMt8sVayfunMQ6a7wrg/MmsVrBnwzYe18iyiPxhzDEVSfKw'...\n[ecs-deploy-runner][2023-02-17T00:24:22+0000] remote: Repository not found.\n[ecs-deploy-runner][2023-02-17T00:24:22+0000] fatal: repository 'https://github.com/org/repo.git/' not found\"><pre class=\"notranslate\"><code class=\"notranslate\">[ecs-deploy-runner][2023-02-17T00:24:22+0000] \t* error downloading 'ssh://git@github.com/org/repo.git?ref=v0.94.1': /usr/bin/git exited with 128: Cloning into '/tmp/tmpltkuc0gw/dev/*********/dev/services/eks-cluster/repo/.terragrunt-cache/KT2kgJFUCMt8sVayfunMQ6a7wrg/MmsVrBnwzYe18iyiPxhzDEVSfKw'...\n[ecs-deploy-runner][2023-02-17T00:24:22+0000] remote: Repository not found.\n[ecs-deploy-runner][2023-02-17T00:24:22+0000] fatal: repository 'https://github.com/org/repo.git/' not found\n</code></pre></div>\n<p dir=\"auto\">For reference, this is trying to clone a private repo. I re-ran a workflow from yesterday, and the <code class=\"notranslate\">plan</code> failed with the above error.</p>\n<hr>\n<ins datetime=\"2023-02-17T00:42:27Z\">\n  <p dir=\"auto\"><a href=\"https://support.gruntwork.io/hc/requests/109908\" rel=\"nofollow\">Tracked in ticket #109908</a></p>\n</ins>","answer":{"body":"All set now. One of my co-workers made a change, which broke something. (Not sure what he did, but it's working now!)","bodyHTML":"<p dir=\"auto\">All set now. One of my co-workers made a change, which broke something. (Not sure what he did, but it's working now!)</p>"}}} />

</CenterLayout>
  

<!-- ##DOCS-SOURCER-START
{
  "sourcePlugin": "github-discussions",
  "hash": "9ffed36d09d76c891b871d931d23c886"
}
##DOCS-SOURCER-END -->
